### ISSUE TITLE
At exportation : 'NoneType' object has no attribute 'checkReadOnlyOnce'

### ISSUE THREAD

**Issue by felix-opera** [BabylonJS/BlenderExporter#22]
Hello,

when i export, i have this error message : 

```
Traceback (most recent call last):
  File "/home/felix/.config/blender/2.80/scripts/addons/babylon_js/__init__.py", line 65, in execute
    exporter.execute(context, self.filepath)
  File "/home/felix/.config/blender/2.80/scripts/addons/babylon_js/json_exporter.py", line 112, in execute
    mesh = Mesh(object, scene, self)
  File "/home/felix/.config/blender/2.80/scripts/addons/babylon_js/mesh.py", line 146, in __init__
    recipe = BakingRecipe(bpyMesh, exporter)
  File "/home/felix/.config/blender/2.80/scripts/addons/babylon_js/materials/baking_recipe.py", line 42, in __init__
    bjsMaterial = BJSMaterial(bpyMaterial, exporter)
  File "/home/felix/.config/blender/2.80/scripts/addons/babylon_js/materials/material.py", line 47, in __init__
    self.checkReadyOnlyOnce = mat.checkReadyOnlyOnce
AttributeError: 'NoneType' object has no attribute 'checkReadyOnlyOnce'

location: <unknown location>:-1
```

i tried to remove all materials of my objects, but the problem stays

thank you

**Comment by Palmer-JC** [comment]
best guess is that there is not even a material slot for this mesh.  Hard
to know with just a stack trace.  Suggest you read the log file yourself.
Find the mesh it was working on at the time of the error.  Look at the
material for that.

**Comment by felix-opera** [comment]
Thank you, i'll investigate with the log file. For now i managed to export by removing all the materials from blender.

**Comment by felix-opera** [comment]
Just for information : The problem occurs when tous try to export a file with an empty material slot. Somehow the Babylon plugin doesn't handle when a slot have no material. Just add an empty material or remove the slot.

**Comment by Palmer-JC** [comment]
Was fixed
