### ISSUE TITLE
Errors in Blender 2.83 while trying to export.

### ISSUE THREAD

**Issue by jcvw75** [BabylonJS/BlenderExporter#24]
Traceback (most recent call last):
  File "C:\Users\jason\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\babylon_js\__init__.py", line 60, in execute
    if not verify_min_blender_version():
  File "C:\Users\jason\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\babylon_js\package_level.py", line 48, in verify_min_blender_version
    minor = int(split2[0])
ValueError: invalid literal for int() with base 10: '83.0'

location: <unknown location>:-1

**Comment by Palmer-JC** [comment]
complete in 2.93 exporter
