### ISSUE TITLE
Error on export (Blender 2.90.1, Windows 10)

### ISSUE THREAD

**Issue by kevinloustau** [BabylonJS/BlenderExporter#33]
Hello,

I'm trying to export using the plugin, but it fails with this issue:
```jsx
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\babylon_js\json_exporter.py", line 47, in execute
    if self.settings.writeCsvFile:
AttributeError: 'NoneType' object has no attribute 'writeCsvFile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\babylon_js\__init__.py", line 65, in execute
    exporter.execute(context, self.filepath)
  File "C:\Users\kevin\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\babylon_js\json_exporter.py", line 170, in execute
    if self.settings.writeCsvFile: stats_handler.close()
AttributeError: 'NoneType' object has no attribute 'writeCsvFile'

location: <unknown location>:-1
```

My setup: 

- Windows 10
- Blender 2.90.1

**Comment by Luluam** [comment]
Hi, Kevin
I found your post about that issue, I've been facing the same for two days. based on the date of your post I think you did manage to find the solution and did overcome the issue. can you please help me fix it?
