### ISSUE TITLE
export of simple blender material failing, issues with blender 2.91

### ISSUE THREAD

**Issue by javismiles** [BabylonJS/BlenderExporter#35]
good day, on a simple cube I have a simple material that just uses a gradient applying it depending on the vertical coordinate of the object, and it fails like this, thank you for your help , I use latest blender version 2.91, and latest babylon versions as well:

I also attach here the simple blend file, thank you again

========= Conversion from Blender to Babylon.js =========
Scene settings used :
Inline textures     :  false
Material Type       :  PBR
Positions Precision :  4
Normals Precision   :  3
UVs Precision       :  3
Vert Color Precision:  3
Mat Weight Precision:  2
Keep Z-up r-handed  :  no
Texture directory   :  C:\MEDIA\
Python World class constructor completed
processing begun of mesh:  dbmassive2.0000
processing begun of material:  Material
WARNING: unsupported node type(ShaderNodeSeparateXYZ) will trigger baking
WARNING: unsupported node type(ShaderNodeMath) will trigger baking
WARNING: unsupported node type(ShaderNodeValToRGB) will trigger baking
usePassDirectHold  False
========= An error was encountered =========
========= end of processing =========
elapsed time:  0 min, 0.01 secs
Python: Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\__init__.py", line 65, in execute
    exporter.execute(context, self.filepath)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\json_exporter.py", line 115, in execute
    mesh = Mesh(object, scene, self)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\mesh.py", line 146, in __init__
    recipe = BakingRecipe(bpyMesh, exporter)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\materials\baking_recipe.py", line 105, in __init__
    self.bakedMaterial.bake(bpyMesh, self)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\materials\material.py", line 127, in bake
    bpy.ops.object.mode_set(mode='EDIT')
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1

[material-issue-blend-file.zip](https://github.com/BabylonJS/BlenderExporter/files/5683904/material-issue-blend-file.zip)

**Comment by javismiles** [comment]
I found the reason, I had to make visible everything in the scene,
thank you :)

**Comment by javismiles** [comment]
actually that worked, but when trying the same now with my final model, which is more complex, it fails with this error, thank you for your help:


========= Conversion from Blender to Babylon.js =========
Scene settings used :
Inline textures     :  false
Material Type       :  PBR
Positions Precision :  4
Normals Precision   :  3
UVs Precision       :  3
Vert Color Precision:  3
Mat Weight Precision:  2
Keep Z-up r-handed  :  no
Texture directory   :  C:\repos\webgl1\public\models\m2\
Python World class constructor completed
processing begun of mesh:  dbmassive2.0000
processing begun of material:  Material
WARNING: unsupported node type(ShaderNodeSeparateXYZ) will trigger baking
WARNING: unsupported node type(ShaderNodeMath) will trigger baking
WARNING: unsupported node type(ShaderNodeValToRGB) will trigger baking
usePassDirectHold  False
========= An error was encountered =========
========= end of processing =========
elapsed time:  0 min, 0.3453 secs
Python: Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\__init__.py", line 65, in execute
    exporter.execute(context, self.filepath)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\json_exporter.py", line 115, in execute
    mesh = Mesh(object, scene, self)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\mesh.py", line 146, in __init__
    recipe = BakingRecipe(bpyMesh, exporter)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\materials\baking_recipe.py", line 105, in __init__
    self.bakedMaterial.bake(bpyMesh, self)
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\babylon_js\materials\material.py", line 139, in bake
    bpy.ops.uv.smart_project(angle_limit = 66.0, island_margin = 0.0, user_area_weight = 1.0, use_aspect = True, stretch_to_bounds = True)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "user_area_weight" unrecognized

location: <unknown location>:-1

**Comment by javismiles** [comment]
seems to be related to this issue:
https://github.com/BabylonJS/BlenderExporter/issues/34

any suggestions to fix it? 
thank you
(im also curious why it doesnt happen with a basic cube, but yes with a more complex model)

https://github.com/BabylonJS/BlenderExporter/issues/34

"The smart_project in Blender 2.83 has the parameter named as user_area_weight.

The parameter has been switched to area_weight in smart_project in Blender 2.91

I think the renaming is causing this issue. Reporting it here so that it can be looked into while porting the exporter for Blender 2.9x"

**Comment by arigbs** [comment]
Having the same issue.
I guess it's best to stay with 2.83 LTS for the time being until the 2.91 api is sufficiently stable for the devs to support.

**Comment by Palmer-JC** [comment]
Changed in exporter for next release, but nothing published yet

**Comment by Palmer-JC** [comment]
complete in 2.93 exporter
