### ISSUE TITLE
Not working with Blender 2.91

### ISSUE THREAD

**Issue by suhaibaffan** [BabylonJS/BlenderExporter#43]
Getting this error:
```
Traceback (most recent call last):
  File "/Users/-----/Library/Application Support/Blender/2.90/scripts/addons/babylon_js/__init__.py", line 65, in execute
    exporter.execute(context, self.filepath)
  File "/Users/****/Library/Application Support/Blender/2.90/scripts/addons/babylon_js/json_exporter.py", line 148, in execute
    bulb = Light(object, self, self.settings.usePBRMaterials)
  File "/Users/----/Library/Application Support/Blender/2.90/scripts/addons/babylon_js/light_shadow.py", line 36, in __init__
    self.define_animations(bpyLight, False, True, False)
  File "/Users/-----/Library/Application Support/Blender/2.90/scripts/addons/babylon_js/f_curve_animatable.py", line 53, in define_animations
    hasData |= posAnimation.append_range(object, animationRange)
UnboundLocalError: local variable 'hasData' referenced before assignment

location: <unknown location>:-1
```

**Comment by Palmer-JC** [comment]
2.91 is not currently supported

**Comment by Palmer-JC** [comment]
Accepted, will be fixed for 2.93 LTS exporter, which is now in development

**Comment by Palmer-JC** [comment]
complete in 2.93 exporter

**Comment by suhaibaffan** [comment]
Thank you @Palmer-JC
